// YouTube Data API adapter — upload a scheduled reel to the Develop Coaching channel.
// POST /youtube/v3/videos (part=snippet,status) with the video bytes as the media body.
// Vertical clips under 3 minutes are auto-classified as Shorts, no special flag needed.
//
// Docs: https://developers.google.com/youtube/v3/docs/videos/insert
//
// Unlike the Meta and LinkedIn adapters, this one streams the video bytes THROUGH
// the function rather than handing the platform a URL to fetch. Meta pulls the
// signed URL itself; YouTube has no such option. That makes this the only adapter
// whose runtime scales with file size, so it runs inside the tick's maxDuration.
//
// Quota: videos.insert costs 1600 units against a default 10,000/day project
// quota, i.e. roughly 6 uploads per day. Fine for one scheduled reel a day,
// but a bulk backfill will exhaust it.
//
// Required env:
//   YOUTUBE_CLIENT_ID
//   YOUTUBE_CLIENT_SECRET
//   YOUTUBE_REFRESH_TOKEN   (generated by greg-brain scripts/youtube-oauth.mjs)

import { Readable } from "stream";
import { google } from "googleapis";
import type { PublishPayload, PublishResult } from "./types";

const MAX_TITLE = 100;
const MAX_DESCRIPTION = 5000;
const MAX_TAGS = 15;
const CATEGORY_PEOPLE_AND_BLOGS = "22";

export function youTubeConfigured(): boolean {
  return !!(
    process.env.YOUTUBE_CLIENT_ID &&
    process.env.YOUTUBE_CLIENT_SECRET &&
    process.env.YOUTUBE_REFRESH_TOKEN
  );
}

export function youTubeClient() {
  const auth = new google.auth.OAuth2(
    process.env.YOUTUBE_CLIENT_ID,
    process.env.YOUTUBE_CLIENT_SECRET
  );
  auth.setCredentials({ refresh_token: process.env.YOUTUBE_REFRESH_TOKEN });
  return google.youtube({ version: "v3", auth });
}

// The row carries only a caption, but YouTube requires a title. Take the first
// non-empty line, same convention as the greg-brain CLI, so a caption written
// for the feed still yields a sensible title. Pure, so it is unit-checkable.
export function deriveTitle(caption: string): string {
  const firstLine = caption
    .split("\n")
    .map((l) => l.trim())
    .find((l) => l.length > 0 && !l.startsWith("#"));
  const title = firstLine || "Develop Coaching";
  return title.length > MAX_TITLE ? `${title.slice(0, MAX_TITLE - 1).trimEnd()}…` : title;
}

// Hashtags in the caption double as YouTube tags. Pure, unit-checkable.
export function deriveTags(caption: string): string[] {
  const tags: string[] = [];
  const matches = Array.from(caption.match(/#\w+/g) || []);
  for (const raw of matches) {
    const tag = raw.slice(1).toLowerCase();
    if (tags.indexOf(tag) === -1) tags.push(tag);
    if (tags.length >= MAX_TAGS) break;
  }
  return tags;
}

export type YouTubePrivacy = "public" | "unlisted" | "private";

export interface PublishToYouTubeOptions {
  // Defaults to "public" for the scheduled path. Overridable so a live
  // end-to-end check can upload unlisted without exposing the channel.
  privacy?: YouTubePrivacy;
}

export async function publishToYouTube(
  payload: PublishPayload,
  opts: PublishToYouTubeOptions = {}
): Promise<PublishResult> {
  if (!youTubeConfigured()) {
    return {
      success: false,
      platform: "youtube",
      error: "YouTube not configured (YOUTUBE_CLIENT_ID / YOUTUBE_CLIENT_SECRET / YOUTUBE_REFRESH_TOKEN)",
    };
  }

  // YouTube is video-only. An image post scheduled here can never succeed, so
  // fail loudly rather than uploading something meaningless.
  if (!payload.videoUrl) {
    return {
      success: false,
      platform: "youtube",
      error: "YouTube requires a video — none on post",
    };
  }

  const caption = payload.caption || "";

  try {
    // Stream the signed URL straight into the upload instead of buffering the
    // whole file in memory; these are tens of megabytes.
    const videoRes = await fetch(payload.videoUrl, { cache: "no-store" });
    if (!videoRes.ok || !videoRes.body) {
      return {
        success: false,
        platform: "youtube",
        error: `fetch video failed: ${videoRes.status}`,
      };
    }

    const yt = youTubeClient();
    const res = await yt.videos.insert({
      part: ["snippet", "status"],
      requestBody: {
        snippet: {
          title: deriveTitle(caption),
          description: caption.slice(0, MAX_DESCRIPTION),
          tags: deriveTags(caption),
          categoryId: CATEGORY_PEOPLE_AND_BLOGS,
        },
        status: {
          privacyStatus: opts.privacy || "public",
          selfDeclaredMadeForKids: false,
        },
      },
      media: {
        body: Readable.fromWeb(videoRes.body as Parameters<typeof Readable.fromWeb>[0]),
      },
    });

    const id = res.data.id;
    if (!id) {
      return {
        success: false,
        platform: "youtube",
        error: `YouTube upload returned no video id: ${JSON.stringify(res.data).slice(0, 300)}`,
      };
    }

    return {
      success: true,
      platform: "youtube",
      externalId: id,
      externalUrl: `https://youtube.com/shorts/${id}`,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      platform: "youtube",
      error: `YouTube upload failed: ${message.slice(0, 400)}`,
    };
  }
}
